import {
  InfluencerProfile,
  BusinessProfile,
  Campaign,
  ApplicationOrInvitation,
  AgreementBrief,
  Conversation,
  ChatMessage,
  Deliverable,
  RatingReview,
  AppNotification,
  User,
} from '../src/types.js';

export const initialUsers: User[] = [
  {
    id: 'user_inf_1',
    email: 'valeria@influconnect.demo',
    role: 'influencer',
    name: 'Valeria Ríos',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'user_inf_2',
    email: 'carlos@influconnect.demo',
    role: 'influencer',
    name: 'Carlos Mendoza',
    createdAt: '2026-01-15T12:00:00Z',
  },
  {
    id: 'user_inf_3',
    email: 'sofia@influconnect.demo',
    role: 'influencer',
    name: 'Sofía Chen',
    createdAt: '2026-02-01T14:30:00Z',
  },
  {
    id: 'user_biz_1',
    email: 'contacto@gourmetbistro.demo',
    role: 'business',
    name: 'Gourmet Bistro & Deli',
    createdAt: '2026-01-05T09:00:00Z',
  },
  {
    id: 'user_biz_2',
    email: 'marketing@aurafashion.demo',
    role: 'business',
    name: 'Aura Eco-Fashion',
    createdAt: '2026-01-08T11:00:00Z',
  },
  {
    id: 'user_biz_3',
    email: 'collabs@technova.demo',
    role: 'business',
    name: 'TechNova Gadgets',
    createdAt: '2026-01-20T16:00:00Z',
  },
];

export const initialInfluencers: InfluencerProfile[] = [
  {
    id: 'inf_1',
    userId: 'user_inf_1',
    fullName: 'Valeria Ríos',
    handle: '@valerios_style',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    bio: 'Creadora apasionada de moda sostenible, estilismo diario y viajes. Amo contar historias auténticas.',
    age: 24,
    gender: 'femenino',
    rating: 4.9,
    reviewCount: 18,
    niche: 'Moda y Estilo',
    socialFollowers: {
      tiktok: 185000,
      instagram: 142000,
      facebook: 35000,
      youtube: 18000,
    },
    location: 'Madrid / Barcelona',
    coverage: 'ambas',
    rates: {
      story: 85,
      reel: 240,
      post: 160,
      videoDedicado: 450,
    },
    portfolio: [
      {
        id: 'vid_1',
        title: '3 Looks de Primavera con Prendas Básicas',
        thumbnailUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-fashion-model-posing-in-neon-lights-39874-large.mp4',
        likes: 24500,
        views: 189000,
        platform: 'tiktok',
        isFeatured: true,
      },
      {
        id: 'vid_2',
        title: 'Haul Consciente & Cápsula Minimalista',
        thumbnailUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-woman-walking-on-city-street-40917-large.mp4',
        likes: 18200,
        views: 142000,
        platform: 'instagram',
        isFeatured: true,
      },
      {
        id: 'vid_3',
        title: 'Cómo Combinar Accesorios para Oficina',
        thumbnailUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&auto=format&fit=crop&q=80',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-young-woman-with-shopping-bags-41005-large.mp4',
        likes: 9400,
        views: 88000,
        platform: 'tiktok',
        isFeatured: false,
      },
    ],
    verified: true,
  },
  {
    id: 'inf_2',
    userId: 'user_inf_2',
    fullName: 'Carlos Mendoza',
    handle: '@carlos_fitpro',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    bio: 'Entrenador funcional y creador de contenido de nutrición y bienestar. Motivación diaria con respaldo científico.',
    age: 28,
    gender: 'masculino',
    rating: 4.8,
    reviewCount: 14,
    niche: 'Fitness y Salud',
    socialFollowers: {
      tiktok: 310000,
      instagram: 98000,
      facebook: 42000,
      youtube: 55000,
    },
    location: 'Barcelona',
    coverage: 'ambas',
    rates: {
      story: 90,
      reel: 260,
      post: 170,
      videoDedicado: 500,
    },
    portfolio: [
      {
        id: 'vid_4',
        title: 'Rutina HIIT de 15 Minutos para Principiantes',
        thumbnailUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
        likes: 31200,
        views: 290000,
        platform: 'tiktok',
        isFeatured: true,
      },
      {
        id: 'vid_5',
        title: 'Mitos del Desayuno Saludable',
        thumbnailUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=600&auto=format&fit=crop&q=80',
        likes: 19800,
        views: 165000,
        platform: 'instagram',
        isFeatured: true,
      },
    ],
    verified: true,
  },
  {
    id: 'inf_3',
    userId: 'user_inf_3',
    fullName: 'Sofía Chen',
    handle: '@sofi.foodie',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    bio: 'Explorando las mejores joyas culinarias, brunchs acogedores y recetas irresistibles. Filmación con calidad cinematográfica.',
    age: 25,
    gender: 'femenino',
    rating: 5.0,
    reviewCount: 22,
    niche: 'Gastronomía y Cafés',
    socialFollowers: {
      tiktok: 220000,
      instagram: 185000,
      facebook: 15000,
      youtube: 12000,
    },
    location: 'Valencia / Madrid',
    coverage: 'presencial',
    rates: {
      story: 75,
      reel: 230,
      post: 140,
      videoDedicado: 420,
    },
    portfolio: [
      {
        id: 'vid_6',
        title: 'Ruta del Mejor Café de Especialidad',
        thumbnailUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&auto=format&fit=crop&q=80',
        likes: 42000,
        views: 380000,
        platform: 'tiktok',
        isFeatured: true,
      },
    ],
    verified: true,
  },
  {
    id: 'inf_4',
    userId: 'user_inf_4',
    fullName: 'Lucas Navarro',
    handle: '@lucas_techreviews',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    bio: 'Gadgets, setups minimalistas e inteligencia artificial explicada sin rodeos. Análisis rigurosos y tomas macro 4K.',
    age: 29,
    gender: 'masculino',
    rating: 4.7,
    reviewCount: 16,
    niche: 'Tecnología y Gadgets',
    socialFollowers: {
      tiktok: 420000,
      instagram: 110000,
      facebook: 28000,
      youtube: 195000,
    },
    location: 'Madrid',
    coverage: 'remota',
    rates: {
      story: 110,
      reel: 320,
      post: 200,
      videoDedicado: 680,
    },
    portfolio: [
      {
        id: 'vid_7',
        title: 'Los mejores accesorios de escritorio 2026',
        thumbnailUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80',
        likes: 28900,
        views: 240000,
        platform: 'youtube',
        isFeatured: true,
      },
    ],
    verified: true,
  },
];

export const initialBusinesses: BusinessProfile[] = [
  {
    id: 'biz_1',
    userId: 'user_biz_1',
    companyName: 'Gourmet Bistro & Deli',
    logoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&auto=format&fit=crop&q=80',
    category: 'Gastronomía y Restaurantes',
    description: 'Bistró artesanal enfocado en cocina fusión de autor y repostería gourmet con ingredientes locales.',
    location: 'Madrid Centro',
    rating: 4.9,
    reviewCount: 24,
    website: 'https://gourmetbistro.example.com',
    verified: true,
  },
  {
    id: 'biz_2',
    userId: 'user_biz_2',
    companyName: 'Aura Eco-Fashion',
    logoUrl: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=400&auto=format&fit=crop&q=80',
    category: 'Moda y Calzado Sostenible',
    description: 'Marca española de prendas de algodón orgánico con diseño atemporal y tintes botánicos sin residuos.',
    location: 'Barcelona',
    rating: 4.8,
    reviewCount: 19,
    website: 'https://aurafashion.example.com',
    verified: true,
  },
  {
    id: 'biz_3',
    userId: 'user_biz_3',
    companyName: 'TechNova Gadgets',
    logoUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&auto=format&fit=crop&q=80',
    category: 'Tecnología y Audio',
    description: 'Fabricantes de gadgets de audio inalámbrico con cancelación de ruido de última generación y diseño escandinavo.',
    location: 'Valencia / Online',
    rating: 4.9,
    reviewCount: 31,
    website: 'https://technova.example.com',
    verified: true,
  },
];

export const initialCampaigns: Campaign[] = [
  {
    id: 'camp_1',
    businessId: 'biz_1',
    businessName: 'Gourmet Bistro & Deli',
    businessLogo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&auto=format&fit=crop&q=80',
    title: 'Lanzamiento Menú Brunch de Temporada Primavera',
    description: 'Buscamos creadores gastronómicos y de lifestyle para una experiencia gastronómica presencial. Queremos tomas atractivas del emplatado, ambiente y reseña honesta con llamado a reserva.',
    niche: 'Gastronomía y Cafés',
    budget: 350,
    requiredNetworks: ['TikTok', 'Instagram'],
    contentType: '1 Reel / TikTok + 3 Stories en vivo',
    minFollowers: 50000,
    location: 'Madrid Centro',
    coverage: 'presencial',
    deadline: '2026-10-25',
    influencersNeeded: 3,
    applicantsCount: 4,
    status: 'abierta',
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'camp_2',
    businessId: 'biz_2',
    businessName: 'Aura Eco-Fashion',
    businessLogo: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=400&auto=format&fit=crop&q=80',
    title: 'Campaña Cápsula Primavera: Moda Lenta y Elegante',
    description: 'Enviaremos un pack de 3 prendas de nuestra nueva colección. El creador debe mostrar combinaciones versátiles, destacando la textura del lino natural y la durabilidad de las costuras.',
    niche: 'Moda y Estilo',
    budget: 450,
    requiredNetworks: ['Instagram', 'TikTok'],
    contentType: '1 Reel estético + 2 Stories con enlace',
    minFollowers: 80000,
    location: 'Nacional / Toda España',
    coverage: 'remota',
    deadline: '2026-10-30',
    influencersNeeded: 2,
    applicantsCount: 6,
    status: 'en_negociacion',
    createdAt: '2026-09-05T14:00:00Z',
  },
  {
    id: 'camp_3',
    businessId: 'biz_3',
    businessName: 'TechNova Gadgets',
    businessLogo: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&auto=format&fit=crop&q=80',
    title: 'Review Tech Auriculares NovaPro ANC',
    description: 'Buscamos creadores de tecnología para unboxing detallado, prueba de cancelación de ruido en ambiente ruidoso y opinión sobre la batería de 48 horas.',
    niche: 'Tecnología y Gadgets',
    budget: 600,
    requiredNetworks: ['YouTube', 'TikTok'],
    contentType: 'Video dedicado o integración de 90 segundos',
    minFollowers: 100000,
    location: 'Cualquier ciudad',
    coverage: 'remota',
    deadline: '2026-11-10',
    influencersNeeded: 4,
    applicantsCount: 2,
    status: 'abierta',
    createdAt: '2026-09-10T09:30:00Z',
  },
];

export const initialApplications: ApplicationOrInvitation[] = [
  {
    id: 'app_1',
    campaignId: 'camp_2',
    campaignTitle: 'Campaña Cápsula Primavera: Moda Lenta y Elegante',
    influencerId: 'inf_1',
    influencerName: 'Valeria Ríos',
    influencerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    businessId: 'biz_2',
    businessName: 'Aura Eco-Fashion',
    businessLogo: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=400&auto=format&fit=crop&q=80',
    type: 'postulacion',
    initiatedBy: 'influencer',
    status: 'aceptada',
    pitchMessage: 'Me encanta la filosofía de Aura. Mi audiencia femenina busca constantemente alternativas sustentables de alta calidad.',
    agreedBudget: 450,
    createdAt: '2026-09-06T11:00:00Z',
    agreementId: 'agr_1',
  },
  {
    id: 'app_2',
    campaignId: 'camp_1',
    campaignTitle: 'Lanzamiento Menú Brunch de Temporada Primavera',
    influencerId: 'inf_3',
    influencerName: 'Sofía Chen',
    influencerAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    businessId: 'biz_1',
    businessName: 'Gourmet Bistro & Deli',
    businessLogo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&auto=format&fit=crop&q=80',
    type: 'invitacion',
    initiatedBy: 'business',
    status: 'pendiente',
    pitchMessage: 'Hola Sofía, tu estética en video es ideal para transmitir la calidez de nuestro nuevo brunch en Madrid Centro.',
    agreedBudget: 350,
    createdAt: '2026-09-12T15:20:00Z',
  },
  {
    id: 'app_3',
    campaignId: 'camp_3',
    campaignTitle: 'Review Tech Auriculares NovaPro ANC',
    influencerId: 'inf_4',
    influencerName: 'Lucas Navarro',
    influencerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    businessId: 'biz_3',
    businessName: 'TechNova Gadgets',
    businessLogo: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&auto=format&fit=crop&q=80',
    type: 'postulacion',
    initiatedBy: 'influencer',
    status: 'pendiente',
    pitchMessage: 'Tengo preparado un segmento comparativo con micro-tomas de sonido donde los NovaPro encajarían perfectamente.',
    agreedBudget: 600,
    createdAt: '2026-09-14T18:00:00Z',
  },
];

export const initialAgreements: AgreementBrief[] = [
  {
    id: 'agr_1',
    applicationId: 'app_1',
    campaignId: 'camp_2',
    campaignTitle: 'Campaña Cápsula Primavera: Moda Lenta y Elegante',
    influencerId: 'inf_1',
    influencerName: 'Valeria Ríos',
    businessId: 'biz_2',
    businessName: 'Aura Eco-Fashion',
    requestedWork: '1 Reel dinámico de 30-45s mostrando 3 combinaciones con el vestido de lino y blazer + 2 Stories con sticker de enlace.',
    agreedBudget: 450,
    platformFeePercent: 10,
    influencerPayout: 405, // 450 - 10%
    deadline: '2026-10-20',
    keyRequirements: [
      'Iluminación natural y tomas en alta definición (1080x1920)',
      'Mencionar el código AURA15 en el copy y en las Stories',
      'Etiquetar a @aura_ecofashion en la primera línea del caption',
      'Entregar borrador previo para validación de claims ecológicos',
    ],
    escrowStatus: 'fondos_retenidos',
    createdAt: '2026-09-07T09:00:00Z',
    depositedAt: '2026-09-07T09:30:00Z',
  },
];

export const initialConversations: Conversation[] = [
  {
    id: 'conv_1',
    agreementId: 'agr_1',
    campaignId: 'camp_2',
    campaignTitle: 'Campaña Cápsula Primavera: Moda Lenta y Elegante',
    influencerId: 'inf_1',
    influencerName: 'Valeria Ríos',
    influencerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    businessId: 'biz_2',
    businessName: 'Aura Eco-Fashion',
    businessLogo: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=400&auto=format&fit=crop&q=80',
    unreadCountInfluencer: 0,
    unreadCountBusiness: 1,
    lastMessageText: '¡Hola Aura! Ya he recibido las prendas y están preciosas. Ya estoy editando el borrador del Reel.',
    lastMessageTimestamp: '2026-09-15T16:20:00Z',
  },
];

export const initialMessages: Record<string, ChatMessage[]> = {
  conv_1: [
    {
      id: 'msg_1',
      conversationId: 'conv_1',
      senderId: 'user_biz_2',
      senderRole: 'business',
      senderName: 'Aura Eco-Fashion',
      senderAvatar: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=400&auto=format&fit=crop&q=80',
      text: '¡Hola Valeria! Bienvenida a la campaña. Hemos confirmado el acuerdo y depositado los $450 USD en el sistema de custodia (escrow). Ya enviamos tu paquete con número de seguimiento ES-883921.',
      timestamp: '2026-09-07T09:35:00Z',
    },
    {
      id: 'msg_2',
      conversationId: 'conv_1',
      senderId: 'user_inf_1',
      senderRole: 'influencer',
      senderName: 'Valeria Ríos',
      senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      text: '¡Genial! Muchas gracias por la confianza. Estaré atenta a la entrega de la paquetería.',
      timestamp: '2026-09-07T10:15:00Z',
    },
    {
      id: 'msg_3',
      conversationId: 'conv_1',
      senderId: 'user_inf_1',
      senderRole: 'influencer',
      senderName: 'Valeria Ríos',
      senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      text: '¡Hola Aura! Ya he recibido las prendas y están preciosas. Ya estoy editando el borrador del Reel.',
      timestamp: '2026-09-15T16:20:00Z',
    },
  ],
};

export const initialDeliverables: Deliverable[] = [
  {
    id: 'deliv_1',
    agreementId: 'agr_1',
    campaignId: 'camp_2',
    influencerId: 'inf_1',
    title: 'Borrador Reel Primavera + Stories',
    contentUrl: 'https://instagram.com/p/reel-draft-valeria-aura-demo',
    previewImageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80',
    notes: 'Adjunto enlace con la vista previa del Reel con música en tendencia y el guión de las 2 Stories adjuntas.',
    submittedAt: '2026-09-16T11:00:00Z',
    status: 'en_revision',
  },
];

export const initialRatings: RatingReview[] = [
  {
    id: 'rev_1',
    campaignId: 'camp_historical_1',
    campaignTitle: 'Campaña Otoño Minimalista',
    agreementId: 'agr_hist_1',
    fromUserId: 'user_biz_2',
    fromUserName: 'Aura Eco-Fashion',
    fromUserRole: 'business',
    toUserId: 'user_inf_1',
    stars: 5,
    comment: 'Valeria entregó antes de la fecha límite y el engagement superó nuestras expectativas. ¡100% recomendada!',
    punctualityScore: 5,
    communicationScore: 5,
    createdAt: '2026-02-20T10:00:00Z',
  },
  {
    id: 'rev_2',
    campaignId: 'camp_historical_1',
    campaignTitle: 'Campaña Otoño Minimalista',
    agreementId: 'agr_hist_1',
    fromUserId: 'user_inf_1',
    fromUserName: 'Valeria Ríos',
    fromUserRole: 'influencer',
    toUserId: 'user_biz_2',
    stars: 5,
    comment: 'Excelente comunicación, brief súper claro y liberación de pago instantánea al aprobar el contenido.',
    punctualityScore: 5,
    communicationScore: 5,
    createdAt: '2026-02-20T12:00:00Z',
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: 'notif_1',
    userId: 'user_inf_1',
    title: '¡Postulación Aceptada y Fondos en Custodia!',
    message: 'Aura Eco-Fashion aceptó tu postulación y depositó $450 USD en el sistema de garantía.',
    type: 'acuerdo',
    read: false,
    createdAt: '2026-09-07T09:30:00Z',
    actionTab: 'messages',
    relatedId: 'agr_1',
  },
  {
    id: 'notif_2',
    userId: 'user_biz_2',
    title: 'Nuevo entregable recibido',
    message: 'Valeria Ríos ha subido el entregable para la campaña Cápsula Primavera.',
    type: 'mensaje',
    read: false,
    createdAt: '2026-09-16T11:00:00Z',
    actionTab: 'messages',
    relatedId: 'deliv_1',
  },
  {
    id: 'notif_3',
    userId: 'user_inf_3',
    title: '¡Nueva Invitación de Marca!',
    message: 'Gourmet Bistro & Deli te ha invitado a participar en "Lanzamiento Menú Brunch".',
    type: 'invitacion',
    read: false,
    createdAt: '2026-09-12T15:20:00Z',
    actionTab: 'applications',
    relatedId: 'app_2',
  },
];
